In [0]:
import os
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

In [0]:
os.mkdir("./dir01")   #Directory 생성

In [0]:
os.getcwd()  #현재위치

'/content'

In [0]:
os.chdir(os.getcwd()+'/dir01') #Directory 이동

In [0]:
print(os.getcwd)

<built-in function getcwd>

In [0]:
os.mkdir('./dir02')  #Directory 생성

In [0]:
os.rmdir('./dir02')  #Directory 삭제

In [0]:
os.path.exists('../Test/untitled0.py')   #file 또는 Directory 유무

False

In [0]:
os.remove('../Test/untitled0.py')  #파일 삭제

FileNotFoundError: ignored

In [0]:
#Try - Data Preprocessing

In [0]:
#fillna
df = pd.DataFrame(np.random.randn(3,3), index = ['a','c','e'], columns = ['one', 'two', 'three'])

In [0]:
df

        one       two     three
a -1.983194  0.423881  1.301086
c -0.480578 -0.135483 -2.001199
e -0.913833  1.368429  0.212071

In [0]:
df = df.reindex(['a', 'b','c'])
df

        one       two     three
a -1.983194  0.423881  1.301086
b       NaN       NaN       NaN
c -0.480578 -0.135483 -2.001199

In [0]:
df = df.fillna(1)

In [0]:
df

        one       two     three
a -1.983194  0.423881  1.301086
b  1.000000  1.000000  1.000000
c -0.480578 -0.135483 -2.001199

In [0]:
#dropna

df = pd.DataFrame(np.random.randn(5,3), index=['a', 'c', 'e', 'f', 'h'], columns = ['one', 'two', 'three'])
df

        one       two     three
a  0.349113 -2.321408 -1.333487
c -0.774431 -1.158522 -0.562585
e  0.437239 -0.705897  0.170839
f -1.116346  1.495318 -1.354620
h  0.796325 -0.266428 -0.800082

In [0]:
df = df.reindex(['a','b','c','d','e','f','g','h'])
df

        one       two     three
a  0.349113 -2.321408 -1.333487
b       NaN       NaN       NaN
c -0.774431 -1.158522 -0.562585
d       NaN       NaN       NaN
e  0.437239 -0.705897  0.170839
f -1.116346  1.495318 -1.354620
g       NaN       NaN       NaN
h  0.796325 -0.266428 -0.800082

In [0]:
df.dropna()

        one       two     three
a  0.349113 -2.321408 -1.333487
c -0.774431 -1.158522 -0.562585
e  0.437239 -0.705897  0.170839
f -1.116346  1.495318 -1.354620
h  0.796325 -0.266428 -0.800082

In [0]:
#replace

df = pd.DataFrame({'one':[10,20,30,40,50,2000], 'two':[1000,0,30,40,50,60]})

In [0]:
df

    one   two
0    10  1000
1    20     0
2    30    30
3    40    40
4    50    50
5  2000    60

In [0]:
df.replace({1000:10, 2000:60})

   one  two
0   10   10
1   20    0
2   30   30
3   40   40
4   50   50
5   60   60

In [0]:
#astype

data = {'Price':['2500000','2700000'], 'Value':['21','84']}
df = pd.DataFrame(data)
df = df.astype(float)

In [36]:
df

       Price  Value
0  2500000.0   21.0
1  2700000.0   84.0

In [40]:
student_score_dict = [
{'name':'김철수','kor':90, 'eng':'', 'math':0},
{'name':'박제동','kor':70, 'eng':50, 'math':100},
{'name':'홍길동','kor':80, 'eng':None, 'math':''},
{'name':'김철수','kor':90, 'eng':20, 'math':70},
{'name':'장길산','kor':None, 'eng':120, 'math':None},
{'name':'홍길동','kor':80, 'eng':None, 'math':0},
{'name':'정진수','kor':90, 'eng':0, 'math':80},
{'name':'오금순','kor':50, 'eng':70, 'math':None},
{'name':'정만득','kor':None, 'eng':None, 'math':None},
]
df_data = pd.DataFrame(student_score_dict)
df_data

  name   kor   eng  math
0  김철수  90.0           0
1  박제동  70.0    50   100
2  홍길동  80.0  None
3  김철수  90.0    20    70
4  장길산   NaN   120  None
5  홍길동  80.0  None     0
6  정진수  90.0     0    80
7  오금순  50.0    70  None
8  정만득   NaN  None  None

In [41]:
#Check duplication, None Per Column
df_data.describe(include='all')

       name        kor    eng  math
count     9   7.000000    6.0   6.0
unique    7        NaN    6.0   5.0
top     홍길동        NaN  120.0   0.0
freq      2        NaN    1.0   2.0
mean    NaN  78.571429    NaN   NaN
std     NaN  14.638501    NaN   NaN
min     NaN  50.000000    NaN   NaN
25%     NaN  75.000000    NaN   NaN
50%     NaN  80.000000    NaN   NaN
75%     NaN  90.000000    NaN   NaN
max     NaN  90.000000    NaN   NaN

In [42]:
df_data['name'].duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7    False
8    False
Name: name, dtype: bool

In [47]:
df_data['name'].drop_duplicates(keep= 'first')

0    김철수
1    박제동
2    홍길동
4    장길산
6    정진수
7    오금순
8    정만득
Name: name, dtype: object

In [50]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    9 non-null      object
 1   kor     7 non-null      float64
 2   eng     6 non-null      object
 3   math    6 non-null      object
dtypes: float64(1), object(3)
memory usage: 416.0+ bytes

In [51]:
df_data.isnull().sum()

name    0
kor     2
eng     3
math    3
dtype: int64

In [52]:
df_data['name'].value_counts()

홍길동    2
김철수    2
장길산    1
정만득    1
오금순    1
박제동    1
정진수    1
Name: name, dtype: int64

In [53]:
df_data['kor'].fillna(df_data['kor'].mean())

0    90.000000
1    70.000000
2    80.000000
3    90.000000
4    78.571429
5    80.000000
6    90.000000
7    50.000000
8    78.571429
Name: kor, dtype: float64

In [54]:
df_data.dtypes, df_data.empty

(name     object
 kor     float64
 eng      object
 math     object
 dtype: object, False)

In [64]:
df_data['eng'] = df_data['eng'].replace({'':np.nan}) 
df_data

  name   kor    eng   math
0  김철수  90.0    NaN    0.0
1  박제동  70.0   50.0  100.0
2  홍길동  80.0    NaN   70.0
3  김철수  90.0   20.0   70.0
4  장길산   NaN  120.0   70.0
5  홍길동  80.0    NaN    0.0
6  정진수  90.0    0.0   80.0
7  오금순  50.0   70.0   70.0
8  정만득   NaN    NaN   70.0

In [0]:
df_data['eng'] = df_data['eng'].fillna(df_data['eng'].median())

In [70]:
df_data['math'].replace({'':np.nan}, inplace = True)

TypeError: ignored

In [71]:
df_data

  name   kor    eng   math
0  김철수  90.0   50.0    0.0
1  박제동  70.0   50.0  100.0
2  홍길동  80.0   50.0   70.0
3  김철수  90.0   20.0   70.0
4  장길산   NaN  120.0   70.0
5  홍길동  80.0   50.0    0.0
6  정진수  90.0    0.0   80.0
7  오금순  50.0   70.0   70.0
8  정만득   NaN   50.0   70.0

In [0]:
df_data['math'].fillna(df_data['math'].median(), inplace = True)

In [73]:
df_data

  name   kor    eng   math
0  김철수  90.0   50.0    0.0
1  박제동  70.0   50.0  100.0
2  홍길동  80.0   50.0   70.0
3  김철수  90.0   20.0   70.0
4  장길산   NaN  120.0   70.0
5  홍길동  80.0   50.0    0.0
6  정진수  90.0    0.0   80.0
7  오금순  50.0   70.0   70.0
8  정만득   NaN   50.0   70.0

ValueError: ignored