In [0]:
#변수 선언
students_score = [
                  {'num':'1', 'name': '김철수', 'kor' : 90, 'eng' : 80, 'math': 85},
                  {'num':'2', 'name': '박제동', 'kor' : 90, 'eng' : 85, 'math': 90},
                  {'num':'3', 'name': '홍길동', 'kor' : 80, 'eng' : 80, 'math': 80}
]

In [0]:
#추가
students_score = students_score + [{'num':'4', 'name': '이천웅', 'kor' : 92, 'eng' : 83, 'math': 97}, {'num':'5', 'name': '채은성', 'kor' : 91, 'eng' : 88, 'math': 92}]

In [3]:
students_score

[{'eng': 80, 'kor': 90, 'math': 85, 'name': '김철수', 'num': '1'},
 {'eng': 85, 'kor': 90, 'math': 90, 'name': '박제동', 'num': '2'},
 {'eng': 80, 'kor': 80, 'math': 80, 'name': '홍길동', 'num': '3'},
 {'eng': 83, 'kor': 92, 'math': 97, 'name': '이천웅', 'num': '4'},
 {'eng': 88, 'kor': 91, 'math': 92, 'name': '채은성', 'num': '5'}]

In [0]:
def total_avg(students_score):

  for x, y in enumerate(students_score):
    y['total'] = y['kor'] + y['eng'] + y['math']
    y['avg'] = round((y['kor'] + y['eng'] + y['math']) / 3)

    print('이름 :', y['name'])
    print('총합 :', y['total'])
    print('평균 :', y['avg'])

  return students_score

In [12]:
student_score = total_avg(students_score)

이름 : 김철수
총합 : 255
평균 : 85
이름 : 박제동
총합 : 265
평균 : 88
이름 : 홍길동
총합 : 240
평균 : 80
이름 : 이천웅
총합 : 272
평균 : 91
이름 : 채은성
총합 : 271
평균 : 90

In [13]:
def class_avg(c_avg):
    c_avg = students_score[0]['avg']+students_score[1]['avg']+students_score[2]['avg']+students_score[3]['avg']+students_score[4]['avg']
    print("학급평균 : ", round(c_avg/5))
    return;

class_avg(students_score)

def kor_avg(k_avg):
    k_avg = students_score[0]['kor']+students_score[1]['kor']+students_score[2]['kor']+students_score[3]['kor']+students_score[4]['kor']
    print("국어평균 : ", round(k_avg/5))
    return;

kor_avg(students_score)

def eng_avg(e_avg):
    e_avg = students_score[0]['eng']+students_score[1]['eng']+students_score[2]['eng']+students_score[3]['eng']+students_score[4]['eng']
    print("영어평균 : ", round(e_avg/5))
    return;

eng_avg(students_score)

def math_avg(m_avg):
    m_avg = students_score[0]['math']+students_score[1]['math']+students_score[2]['math']+students_score[3]['math']+students_score[4]['math']
    print("수학평균 : ", round(m_avg/5))
    return;

math_avg(students_score)

학급평균 :  87
국어평균 :  89
영어평균 :  83
수학평균 :  89